[tool.poetry]
name = "python-project-49"
version = "0.1.0"
description = ""
authors = ["zluuba <zluyba.nikitina@gmail.com>"]
readme = "README.md"
# packages = [{include = "python_project_49"}]
packages = [{include = "brain_games"}]

[tool.poetry.scripts]
brain-games = "brain_games.scripts.brain_games:main"

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
